version: '3.4'
services:
  app:
    container_name: weather
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
  
  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - 80:80
    depends_on:
      - app
  
    